FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:232 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0xc0028539 0xc0022973 0xc002b276 0xc0021102
Translation of call stack:
0xc0028539: debug_panic (.../../lib/kernel/debug.c:38)
0xc0022973: lock_release (...../../threads/synch.c:234)
0xc002b276: b_thread_func (...ity-donate-multiple2.c:83)
0xc0021102: kernel_thread (..../../threads/thread.c:457)
